FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "./SugarSociety.Api/SugarSociety.Api.csproj"
RUN dotnet build "./SugarSociety.Api/SugarSociety.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./SugarSociety.Api/SugarSociety.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SugarSociety.Api.dll"]