name: Deploy Application

on:
  push:
    branches:
      - main

jobs:

  deploy-frontend:
    uses: ./.github/workflows/deploy-frontend.yml
    secrets:
      MONGO_DB_CONNECTION_STRING: ${{ secrets.MONGO_DB_CONNECTION_STRING }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      AWS_ECR_REPOSITORY: ${{ vars.AWS_ECR_REPOSITORY }}

  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yml
    secrets:
      MONGO_DB_CONNECTION_STRING: ${{ secrets.MONGO_DB_CONNECTION_STRING }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      AWS_ECR_REPOSITORY: ${{ vars.AWS_ECR_REPOSITORY }}